Backport dfe764e3f85784752d69fd51306644732e808d38
openjdk/jdk20u pull request #86
Opened 2023-07-20 02:52 UTC by airsquared

2023-09-01 03:16 UTC, airsquared commented
Would anyone be able to review this? Even if there isn't going to another JDK 20 release, there could still be other distributions.

2023-09-01 15:24 UTC, phohensee requested changes
Please remove the copyright date update. The result should be clean.

2023-09-01 17:13 UTC, airsquared commented
/integrate

2023-09-01 17:40 UTC, phohensee commented
Tagged the JBS issue.

2023-09-12 16:47 UTC, airsquared commented
I ran the GHA tests here and it seems the tests failing had nothing to do with this change. Linux failed because it couldn't find gcc and Windows failed because it couldn't get jtreg.

2023-10-16 23:49 UTC, closed without merging